"""empty message

Revision ID: 07cd935b5eb3
Revises: 804e09ba7414
Create Date: 2020-12-04 12:34:30.805753

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07cd935b5eb3'
down_revision = '804e09ba7414'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clientprofile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('nombre', sa.String(length=100), nullable=True),
    sa.Column('apellido', sa.String(length=100), nullable=True),
    sa.Column('rut', sa.String(length=100), nullable=True),
    sa.Column('nacionalidad', sa.String(length=100), nullable=True),
    sa.Column('ciudad', sa.String(length=100), nullable=True),
    sa.Column('pais', sa.String(length=100), nullable=True),
    sa.Column('biografia', sa.String(length=100), nullable=True),
    sa.Column('suma_rating', sa.Integer(), nullable=True),
    sa.Column('contrataciones', sa.Integer(), nullable=True),
    sa.Column('feedback', sa.String(length=1000), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('clientprofile')
    # ### end Alembic commands ###
