"""empty message

Revision ID: 183fe8e8ef3a
Revises: 3b98f9503ae3
Create Date: 2020-12-18 19:30:56.677464

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '183fe8e8ef3a'
down_revision = '3b98f9503ae3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gig', sa.Column('artist_name', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('gig', 'artist_name')
    # ### end Alembic commands ###
