"""empty message

Revision ID: 23941aa696d7
Revises: 6821ad5b8f14
Create Date: 2020-12-20 00:01:33.792045

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23941aa696d7'
down_revision = '6821ad5b8f14'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feedback', sa.Column('gig_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'feedback', 'gig', ['gig_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'feedback', type_='foreignkey')
    op.drop_column('feedback', 'gig_id')
    # ### end Alembic commands ###
