"""empty message

Revision ID: 3462908e3bcc
Revises: 23941aa696d7
Create Date: 2020-12-20 00:47:04.363160

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3462908e3bcc'
down_revision = '23941aa696d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feedback', sa.Column('rated_by_client', sa.Boolean(), server_default=sa.text('false'), nullable=True))
    op.add_column('feedback', sa.Column('rated_by_dj', sa.Boolean(), server_default=sa.text('false'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('feedback', 'rated_by_dj')
    op.drop_column('feedback', 'rated_by_client')
    # ### end Alembic commands ###
