"""empty message

Revision ID: 424669c8c424
Revises: 3462908e3bcc
Create Date: 2020-12-20 19:54:42.626480

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '424669c8c424'
down_revision = '3462908e3bcc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('feedback_ibfk_1', 'feedback', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('feedback_ibfk_1', 'feedback', 'gig', ['gig_id'], ['id'])
    # ### end Alembic commands ###
