"""empty message

Revision ID: 6821ad5b8f14
Revises: 70e5cc13b9bb
Create Date: 2020-12-19 23:59:58.798039

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6821ad5b8f14'
down_revision = '70e5cc13b9bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('dj_id', sa.Integer(), nullable=True),
    sa.Column('client_username', sa.String(length=100), nullable=True),
    sa.Column('dj_username', sa.String(length=100), nullable=True),
    sa.Column('dia_evento', sa.String(length=100), nullable=True),
    sa.Column('nombre_evento', sa.String(length=100), nullable=True),
    sa.Column('by_dj_commentary', sa.String(length=1000), nullable=True),
    sa.Column('by_client_commentary', sa.String(length=1000), nullable=True),
    sa.Column('by_dj_rating', sa.Integer(), nullable=True),
    sa.Column('by_client_rating', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('gig', sa.Column('feedback_client', sa.Boolean(), server_default=sa.text('false'), nullable=True))
    op.add_column('gig', sa.Column('feedback_dj', sa.Boolean(), server_default=sa.text('false'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('gig', 'feedback_dj')
    op.drop_column('gig', 'feedback_client')
    op.drop_table('feedback')
    # ### end Alembic commands ###
