"""empty message

Revision ID: 6bbe33acbd3d
Revises: f4f6018443f8
Create Date: 2020-12-18 19:49:24.157039

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6bbe33acbd3d'
down_revision = 'f4f6018443f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('gig_ibfk_4', 'gig', type_='foreignkey')
    op.drop_constraint('gig_ibfk_3', 'gig', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('gig_ibfk_3', 'gig', 'account', ['username_cliente'], ['username'], ondelete='CASCADE')
    op.create_foreign_key('gig_ibfk_4', 'gig', 'account', ['username_dj'], ['username'], ondelete='CASCADE')
    # ### end Alembic commands ###
