"""empty message

Revision ID: 70e5cc13b9bb
Revises: 9314bfa1aa3a
Create Date: 2020-12-18 19:52:35.910173

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70e5cc13b9bb'
down_revision = '9314bfa1aa3a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('djprofile_ibfk_2', 'djprofile', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('djprofile_ibfk_2', 'djprofile', 'account', ['username'], ['username'], ondelete='CASCADE')
    # ### end Alembic commands ###
