"""empty message

Revision ID: 804e09ba7414
Revises: 
Create Date: 2020-12-04 00:22:49.120293

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '804e09ba7414'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('password', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('djprofile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dj_id', sa.Integer(), nullable=True),
    sa.Column('artista', sa.String(length=100), nullable=True),
    sa.Column('ciudad', sa.String(length=100), nullable=True),
    sa.Column('pais', sa.String(length=100), nullable=True),
    sa.Column('mixcloud', sa.String(length=100), nullable=True),
    sa.Column('soundcloud', sa.String(length=100), nullable=True),
    sa.Column('spotify', sa.String(length=100), nullable=True),
    sa.Column('generos', sa.String(length=500), nullable=True),
    sa.Column('servicios', sa.String(length=500), nullable=True),
    sa.Column('tecnica', sa.String(length=500), nullable=True),
    sa.Column('agregar_cancion', sa.Boolean(), server_default=sa.text('false'), nullable=True),
    sa.Column('url_cancion', sa.String(length=100), nullable=True),
    sa.Column('biografia', sa.String(length=1000), nullable=True),
    sa.Column('dur_min', sa.String(length=10), nullable=True),
    sa.Column('dur_max', sa.String(length=10), nullable=True),
    sa.Column('staff', sa.Integer(), nullable=True),
    sa.Column('arrienda_equipos', sa.String(length=10), nullable=True),
    sa.Column('requisitos', sa.String(length=1000), nullable=True),
    sa.Column('datos', sa.String(length=1000), nullable=True),
    sa.Column('suma_rating', sa.Integer(), nullable=True),
    sa.Column('contrataciones', sa.Integer(), nullable=True),
    sa.Column('feedback', sa.String(length=1000), nullable=True),
    sa.ForeignKeyConstraint(['dj_id'], ['account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('djprofile')
    op.drop_table('account')
    op.drop_table('roles')
    # ### end Alembic commands ###
