"""empty message

Revision ID: 91df086c3309
Revises: c2db1c1dbe58
Create Date: 2020-12-14 15:01:18.059835

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91df086c3309'
down_revision = 'c2db1c1dbe58'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gig', sa.Column('time_created', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('gig', 'time_created')
    # ### end Alembic commands ###
