"""empty message

Revision ID: 9314bfa1aa3a
Revises: 6bbe33acbd3d
Create Date: 2020-12-18 19:50:50.952066

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9314bfa1aa3a'
down_revision = '6bbe33acbd3d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'djprofile', 'account', ['username'], ['username'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'djprofile', type_='foreignkey')
    # ### end Alembic commands ###
