"""empty message

Revision ID: bcbedda5b3fc
Revises: 91df086c3309
Create Date: 2020-12-14 16:58:00.175271

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bcbedda5b3fc'
down_revision = '91df086c3309'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gig', sa.Column('duracion', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('gig', 'duracion')
    # ### end Alembic commands ###
