"""empty message

Revision ID: f4f6018443f8
Revises: 183fe8e8ef3a
Create Date: 2020-12-18 19:47:41.560082

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4f6018443f8'
down_revision = '183fe8e8ef3a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'gig', 'account', ['username_cliente'], ['username'], ondelete='CASCADE')
    op.create_foreign_key(None, 'gig', 'account', ['username_dj'], ['username'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'gig', type_='foreignkey')
    op.drop_constraint(None, 'gig', type_='foreignkey')
    # ### end Alembic commands ###
